In [ ]:
#pip install numpy

In [2]:
import numpy as np

#### 1D array

In [3]:
np1 = np.array([1,2,3,4,5])

In [4]:
print(np1)

[1 2 3 4 5]


In [5]:
type(np1)

numpy.ndarray

In [6]:
np2 = np.array((1,2,3,4,5,6))

In [7]:
np2

array([1, 2, 3, 4, 5, 6])

In [8]:
print(np2)

[1 2 3 4 5 6]


In [9]:
type(np2)

numpy.ndarray

#### 2d array

In [10]:
np3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
np3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [14]:
np4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
np3 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)

In [16]:
np3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [17]:
np5 = np.array([5,-1,"s",2])

In [18]:
np5

array(['5', '-1', 's', '2'], dtype='<U21')

In [19]:
np6 = np.array([[2.4,3],[4.4,2],[2.1,1]])

In [20]:
np6

array([[2.4, 3. ],
       [4.4, 2. ],
       [2.1, 1. ]])

In [21]:
np6.ndim

2

In [22]:
np5.ndim

1

In [23]:
np4.ndim

3

In [24]:
np6.shape

(3, 2)

In [25]:
np4.shape

(2, 2, 2)

In [27]:
np5.shape

(4,)

In [28]:
np6.size

6

In [29]:
np4.size

8

In [30]:
np5.size

4

In [31]:
np6.dtype

dtype('float64')

In [32]:
np4.dtype

dtype('int64')

In [33]:
np5.dtype

dtype('<U21')

In [34]:
np6.itemsize

8

In [35]:
np4.itemsize

8

In [36]:
np5.itemsize

84

In [37]:
np4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
np5

array(['5', '-1', 's', '2'], dtype='<U21')

In [39]:
np5[1]

np.str_('-1')

In [40]:
np5[0:2]

array(['5', '-1'], dtype='<U21')

In [41]:
np6

array([[2.4, 3. ],
       [4.4, 2. ],
       [2.1, 1. ]])

In [42]:
np6[1,1]

np.float64(2.0)

In [43]:
np4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [44]:
np4[1,0,1]

np.int64(6)

In [45]:
np1

array([1, 2, 3, 4, 5])

In [46]:
m1 = np.array([True, False, True, False, True])

In [47]:
np1[m1]

array([1, 3, 5])

In [48]:
np3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [49]:
m2 = np.array([[ True, True, False],[True,False,True],[False,False, True]])

In [50]:
m2

array([[ True,  True, False],
       [ True, False,  True],
       [False, False,  True]])

In [51]:
np3[m2]

array([1., 2., 4., 6., 9.])

In [52]:
np3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [54]:
m3 = np.array([[ True, False, True],[False,True,False],[True,False, False]])

In [55]:
np3[m3]

array([1., 3., 5., 7.])

In [56]:
np4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [57]:
m4 = np.array([[[ True, False],[True,False]],[[True,False],[True,False]]])

In [58]:
np4[m4]

array([1, 3, 5, 7])

In [59]:
np3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [60]:
np3[0:2,0:2]

array([[1., 2.],
       [4., 5.]])

In [61]:
np3[1:,1:]

array([[5., 6.],
       [8., 9.]])

In [62]:
np4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [68]:
np4[0:2,0:1,0:1]

array([[[1]],

       [[5]]])

In [70]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [71]:
s = a+b

In [72]:
print(s)

[5 7 9]


In [73]:
c = b / a

In [74]:
print(c)

[4.  2.5 2. ]


In [75]:
a

array([1, 2, 3])

In [78]:
h = a ** 4

In [79]:
h

array([ 1, 16, 81])

In [80]:
m = b % a

In [81]:
m

array([0, 1, 0])

In [82]:
np3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [83]:
np3.transpose()

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [84]:
np3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [85]:
np1

array([1, 2, 3, 4, 5])

In [86]:
np1 = np.array([5,4,3,2,1])

In [87]:
np.sort(np1)

array([1, 2, 3, 4, 5])

In [88]:
np2 = np.array([[5,2,3],[7,1,6],[8,4,9]])

In [89]:
np2

array([[5, 2, 3],
       [7, 1, 6],
       [8, 4, 9]])

In [90]:
np.sort(np2, axis = 0)

array([[5, 1, 3],
       [7, 2, 6],
       [8, 4, 9]])

In [91]:
np.sort(np2, axis = 1)

array([[2, 3, 5],
       [1, 6, 7],
       [4, 8, 9]])

In [92]:
np1

array([5, 4, 3, 2, 1])

In [93]:
np.sort(np1)

array([1, 2, 3, 4, 5])

In [95]:
np.argsort(np1)

array([4, 3, 2, 1, 0])

In [96]:
a

array([1, 2, 3])

In [97]:
b

array([4, 5, 6])

In [98]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [99]:
a

array([1, 2, 3])

In [100]:
c = np.array([4,5])

In [101]:
c

array([4, 5])

In [102]:
np.concatenate((a,c))

array([1, 2, 3, 4, 5])

In [103]:
a1 = np.array([[1,2,3],[4,5,6]])

In [105]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
a2 = np.array([[7,8],[9,10]])

In [106]:
a2

array([[ 7,  8],
       [ 9, 10]])

In [111]:
np.concatenate((a1,a2), axis = 1) #1 for rows and 0 for column

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

In [112]:
n1 = np.array([1,2,3,4,5,6])

In [113]:
n1

array([1, 2, 3, 4, 5, 6])

In [ ]:
n1.reshape(2,3) #to covert to 2D  array

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
n1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
n1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [117]:
n1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [127]:
n1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
n1.reshape(2,3,2) #to covert to 3D array

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [131]:
np2.reshape(-1) #to covert to 1d array

array([5, 2, 3, 7, 1, 6, 8, 4, 9])

In [132]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [133]:
np.split(n1,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

#### mean, median, std, max, min, sum

In [142]:
np2

array([[5, 2, 3],
       [7, 1, 6],
       [8, 4, 9]])

####  axis: 0 is column
####  axis: 1 is rows

In [136]:
np.mean(np2)

np.float64(5.0)

In [137]:
np.mean(np2, axis = 0)

array([6.66666667, 2.33333333, 6.        ])

In [138]:
np.mean(np2, axis = 1)

array([3.33333333, 4.66666667, 7.        ])

In [139]:
np.max(np2)

np.int64(9)

In [140]:
np.min(np2)

np.int64(1)

In [141]:
np.sum(np2, axis=0)

array([20,  7, 18])

In [143]:
np0 = np.zeros(5)

In [144]:
np0

array([0., 0., 0., 0., 0.])

In [149]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [145]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [146]:
np.zeros((2,2,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [147]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [150]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [151]:
np.full((2,4),-1)

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [152]:
np.full((2,4,2),-4)

array([[[-4, -4],
        [-4, -4],
        [-4, -4],
        [-4, -4]],

       [[-4, -4],
        [-4, -4],
        [-4, -4],
        [-4, -4]]])

In [153]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [157]:
np.eye(4,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4,4,3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.eye(4,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
np.eye(4,4,-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [163]:
np.eye(4,4,0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [164]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [168]:
np.arange(3,11,3)

array([3, 6, 9])

In [167]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
np.random.random(5)

array([0.12391535, 0.50158058, 0.59329389, 0.47945737, 0.84302265])

In [172]:
np.random.random((2,3))

array([[0.00319379, 0.42219975, 0.89440921],
       [0.60970331, 0.62376781, 0.11963626]])

In [173]:
np.random.random((2,2,3))


array([[[0.81083614, 0.42962212, 0.78835548],
        [0.46624688, 0.48399317, 0.36167371]],

       [[0.59103602, 0.76630433, 0.91461201],
        [0.66949543, 0.1478193 , 0.3738748 ]]])

In [174]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])