In [1]:
#numpy>> numerical python
#2005 bt tavis oliphant
#before 2005 there were special mathematical tools (similar to Tora, Lingo)

In [2]:
import numpy as np #ap is alias

In [3]:
np.__version__

'2.2.4'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
lis =[1,2,3,"pritam",3+5j,True,1.3] #list stores heterogenous data
type(lis)

list

In [6]:
#Numpy store the data in an numpy array
#an array is a container/data structure use to store data of same type >> homogenous

In [8]:
#why numpy? already we have list, c is one of the fastest programing language after c++
#numpy is built using c>> numpy computation is fast
#due to array>> sice it store only homogenious data, numpy array is faster
#since it stores homogenous data >> contiguous/continous memory location
#Mathematical computation is fast

In [ ]:
l = [1,2,3,4,5] #numpy array is homogenous >> all element can be : integer, float, string

In [ ]:
arr = np.array(l) #numpy.ndarray >> n dimentional array

In [11]:
type(arr)

numpy.ndarray

In [13]:
l = [1,2,3,4,5,"Pritam"]
np.array(l)

array(['1', '2', '3', '4', '5', 'Pritam'], dtype='<U21')

In [14]:
#array stores homogenous data

In [16]:
l = [1,2,3,4,5,2.5]
np.array(l)

array([1. , 2. , 3. , 4. , 5. , 2.5])

In [17]:
l = [1,2,3,4,5,2.5,"data"]
np.array(l)

array(['1', '2', '3', '4', '5', '2.5', 'data'], dtype='<U32')

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr

array([1, 2, 3, 4, 5])

In [21]:
arr.ndim #arr has only rows

1

In [22]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [23]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr1.ndim

2

In [25]:
mat = np.matrix([1,2,3,4]) #matrix is a specialised array of 2 dimension

In [26]:
type(mat)

numpy.matrix

In [27]:
mat.ndim

2

In [28]:
mat

matrix([[1, 2, 3, 4]])

In [29]:
# to understand the dimention, see the no of opening/cloasing square bracket 

In [ ]:
np.matrix([[[1,2],[1,5],[1,6]]]) #error matrix must be 2-dimensional

ValueError: matrix must be 2-dimensional

In [32]:
arr3 = np.array([[[1,2],[1,5],[1,6]]])

In [33]:
arr3

array([[[1, 2],
        [1, 5],
        [1, 6]]])

In [34]:
arr3.ndim

3

In [35]:
#more way to array
l = [1,2,3]
np.asarray(l) #initial function asarray to convert to an array, np.array came after this.

array([1, 2, 3])

In [36]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [38]:
#asanyarray, will covert the input to an andarray, but pass ndarray subclass throws
#if somethis is already an array or part of array, it will simply allow to pass through it

In [39]:
mat

matrix([[1, 2, 3, 4]])

In [40]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [43]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [45]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr

array([1, 2, 3, 4, 5])

In [47]:
#acessing elements of the array
arr[0]

np.int64(1)

In [48]:
#array is mutable
arr[0] = 1000

In [49]:
arr

array([1000,    2,    3,    4,    5])

In [50]:
#a and arr will point to sme memory location, so if there is changes is a or arr >> it will reflect on both
a = arr

In [51]:
a

array([1000,    2,    3,    4,    5])

In [52]:
arr

array([1000,    2,    3,    4,    5])

In [53]:
#shallow copy>> change in one array will lead to change in anoyher

In [54]:
a[0] = 5000

In [55]:
a

array([5000,    2,    3,    4,    5])

In [56]:
arr

array([5000,    2,    3,    4,    5])

In [ ]:
#deep copy >> change in one array it will not affect other
b = arr.copy()

In [58]:
b

array([5000,    2,    3,    4,    5])

In [59]:
b[0] = 1

In [60]:
arr

array([5000,    2,    3,    4,    5])

In [61]:
b

array([1, 2, 3, 4, 5])

In [62]:
#to create an array>> np.array, np.asany array

In [63]:
#multiple approch to generate any array

In [65]:
arr1 = np.fromfunction(lambda i, j: i==j, (3,3)) #construct an array by executing a function over each coordinate

In [66]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [67]:
arr1.ndim

2

In [68]:
arr1.shape #shape of array

(3, 3)

In [69]:
arr1.size #no of element in array

9

In [70]:
#true is stored as 1 and fale 0 in python
True - False

1

In [72]:
arr2 = np.fromfunction(lambda i, j: i*j, (3,3))

In [73]:
arr2.ndim

2

In [74]:
arr2.shape

(3, 3)

In [75]:
arr2.size

9

In [76]:
for i in range(5):
    print(i)

0
1
2
3
4


In [77]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [78]:
(i for i in range(5))

<generator object <genexpr> at 0x00000297DA16AA40>

In [ ]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [80]:
iterator = (i for i in range(5))

In [81]:
iterator

<generator object <genexpr> at 0x00000297DA169070>

In [ ]:
np.fromiter(iterator, int) #create a new 1-d array from an iterable object.

array([0, 1, 2, 3, 4])

In [84]:
np.fromiter(iterator, float)

array([], dtype=float64)

In [ ]:
np.fromstring("22 23 24", sep = " ") #by default is float, value inside string should be numerical

array([22., 23., 24.])

In [85]:
np.fromstring("22 23 24", sep = " ",dtype = int)

array([22, 23, 24])

In [88]:
#for string chracter we have to use split
string = "Pritam, Akash, Nikhil"
string.split(",")

['Pritam', ' Akash', ' Nikhil']

In [89]:
string = "Pritam Akash Nikhil"
string.split(" ")

['Pritam', 'Akash', 'Nikhil']

In [91]:
np.array(string.split(" "))

array(['Pritam', 'Akash', 'Nikhil'], dtype='<U6')

In [92]:
range(10)

range(0, 10)

In [93]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#another method of numpy >> to senerste a sequence of number
np.arange(1,10) #arange return evenly spacified values within a given interval, by default step is 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [98]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [99]:
np.linspace(1,5,10) #give me 10 no between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])