In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))


In [3]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [4]:
arr2

array([[2, 2, 1],
       [2, 2, 1],
       [1, 2, 1]], dtype=int32)

In [5]:
arr1.flatten() #return a copy of the array collapsed into dimension. 

array([1, 1, 1, 2, 1, 2, 1, 2, 1], dtype=int32)

In [6]:
#expand dimension
arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

In [9]:
np.expand_dims(arr, axis=0) #increase the dimension by 1 in the provided axis, 0 means rows (x axis), 1 means coulmnwise(y axis)

array([[1, 2, 3, 4]])

In [10]:
np.expand_dims(arr, axis=1) #increase the dimension by 1 in the provided axis, 0 means rows (x axis), 1 means coulmnwise(y axis)


array([[1],
       [2],
       [3],
       [4]])

In [11]:
np.expand_dims(arr, axis=1).ndim

2

In [12]:
arr= np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
np.expand_dims(arr, axis=0).ndim


3

In [15]:
np.expand_dims(arr, axis=1)


array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [16]:
np.expand_dims(arr, axis=1).ndim


3

In [17]:
a = np.array([[1],[2],[3]])

In [18]:
a

array([[1],
       [2],
       [3]])

In [19]:
a.ndim

2

In [21]:
#squeezing the dimension by 1-D
np.squeeze(a) #remove of length one from 'a'

array([1, 2, 3])

In [23]:
a

array([[1],
       [2],
       [3]])

In [26]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [27]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [28]:
np.repeat(arr1, 2)

array([1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1], dtype=int32)

In [29]:
np.repeat(arr1, 2, axis=0)


array([[1, 1, 1],
       [1, 1, 1],
       [2, 1, 2],
       [2, 1, 2],
       [1, 2, 1],
       [1, 2, 1]], dtype=int32)

In [30]:
np.repeat(arr1, 2, axis=0)


array([[1, 1, 1],
       [1, 1, 1],
       [2, 1, 2],
       [2, 1, 2],
       [1, 2, 1],
       [1, 2, 1]], dtype=int32)

In [31]:
np.repeat(arr2, 2, axis=1)


array([[2, 2, 2, 2, 1, 1],
       [2, 2, 2, 2, 1, 1],
       [1, 1, 2, 2, 1, 1]], dtype=int32)

In [32]:
a

array([[1],
       [2],
       [3]])

In [34]:
np.roll(a,-1) #shift place

array([[2],
       [3],
       [1]])

In [35]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [36]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])

In [37]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
np.roll(c, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [40]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
np.roll(c, 2)


array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [46]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [47]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [48]:
arr2

array([[2, 2, 1],
       [2, 2, 1],
       [1, 2, 1]], dtype=int32)

In [49]:
arr1 + arr2

array([[3, 3, 2],
       [4, 3, 3],
       [2, 4, 2]], dtype=int32)

In [50]:
arr1-arr2

array([[-1, -1,  0],
       [ 0, -1,  1],
       [ 0,  0,  0]], dtype=int32)

In [51]:
arr1 * arr2

array([[2, 2, 1],
       [4, 2, 2],
       [1, 4, 1]], dtype=int32)

In [52]:
arr1 > arr2

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [53]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [54]:
~arr1

array([[-2, -2, -2],
       [-3, -2, -3],
       [-2, -3, -2]], dtype=int32)

In [57]:
#operations on numpy string array
d = np.array(["pritam","skills"])
d

array(['pritam', 'skills'], dtype='<U6')

In [58]:
np.char.upper(d)

array(['PRITAM', 'SKILLS'], dtype='<U6')

In [59]:
np.char.capitalize(d)

array(['Pritam', 'Skills'], dtype='<U6')

In [60]:
#mathamatical function

In [61]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [62]:
np.sin(arr1)

array([[0.84147098, 0.84147098, 0.84147098],
       [0.90929743, 0.84147098, 0.90929743],
       [0.84147098, 0.90929743, 0.84147098]])

In [63]:
np.cos(arr1)

array([[ 0.54030231,  0.54030231,  0.54030231],
       [-0.41614684,  0.54030231, -0.41614684],
       [ 0.54030231, -0.41614684,  0.54030231]])

In [64]:
np.tan(arr1)

array([[ 1.55740772,  1.55740772,  1.55740772],
       [-2.18503986,  1.55740772, -2.18503986],
       [ 1.55740772, -2.18503986,  1.55740772]])

In [65]:
np.log10(arr1)

array([[0.     , 0.     , 0.     ],
       [0.30103, 0.     , 0.30103],
       [0.     , 0.30103, 0.     ]])

In [66]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [67]:
np.power(arr1, 3)

array([[1, 1, 1],
       [8, 1, 8],
       [1, 8, 1]], dtype=int32)

In [68]:
np.max(arr1)

np.int32(2)

In [69]:
np.min(arr1)

np.int32(1)

In [70]:
np.mean(arr1)

np.float64(1.3333333333333333)

In [71]:
np.std(arr1)

np.float64(0.4714045207910317)

In [72]:
np.var(arr1)

np.float64(0.2222222222222222)

In [73]:
arr1 - arr2

array([[-1, -1,  0],
       [ 0, -1,  1],
       [ 0,  0,  0]], dtype=int32)

In [74]:
np.subtract(arr1, arr2)

array([[-1, -1,  0],
       [ 0, -1,  1],
       [ 0,  0,  0]], dtype=int32)

In [75]:
arr1 * arr2

array([[2, 2, 1],
       [4, 2, 2],
       [1, 4, 1]], dtype=int32)

In [76]:
np.multiply(arr1,arr2)

array([[2, 2, 1],
       [4, 2, 2],
       [1, 4, 1]], dtype=int32)

In [77]:
np.mod(arr1,arr2) #return element wise remainder

array([[1, 1, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

In [78]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [79]:
#sorting and searching in numpy array
e = np.array([5,6,1,2])
e

array([5, 6, 1, 2])

In [81]:
np.sort(e) #Return a sorted copy of an array.

array([1, 2, 5, 6])

In [82]:
f = np.array([5,199,200,6,7,8])
f

array([  5, 199, 200,   6,   7,   8])

In [83]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [84]:
np.searchsorted(f, 170) #Find indices where elements should be inserted to maintain order.

np.int64(6)

In [85]:
f = np.array([5,199,200,0,0,0,0,0,6,7,8])
f

array([  5, 199, 200,   0,   0,   0,   0,   0,   6,   7,   8])

In [88]:
np.count_nonzero(f)

6

In [89]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [90]:
np.where(f>0) #same as above condition

(array([ 0,  1,  2,  8,  9, 10]),)

In [93]:
np.extract(f>0,f) #same as above condition

array([  5, 199, 200,   6,   7,   8])

In [94]:
f

array([  5, 199, 200,   0,   0,   0,   0,   0,   6,   7,   8])

In [96]:
f.byteswap() #swap the bytes of the array element

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
                          0,                    0,                    0,
                          0,                    0,   432345564227567616,
         504403158265495552,   576460752303423488])

In [97]:
import numpy.matlib as nm

In [98]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [99]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [100]:
#nmpy linear algebra

In [101]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [102]:
arr2

array([[2, 2, 1],
       [2, 2, 1],
       [1, 2, 1]], dtype=int32)

In [103]:
arr1 @ arr2

array([[ 5,  6,  3],
       [ 8, 10,  5],
       [ 7,  8,  4]], dtype=int32)

In [104]:
np.linalg.det(arr1)

np.float64(0.0)

In [105]:
np.linalg.det(arr2)


np.float64(0.0)

In [110]:
# in matrix we can not deviede by another matrix, you have inverse
#np.linalg.inv()

In [111]:
a = np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]]) 
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [112]:
b = np.array([16,8,0])

In [113]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])

In [ ]:
'''
7x + 5.3y - 3z = 18
2x + 3y - 2z = 8
3x + 5y - 3z = 0
'''
#linalg example

'\n7x + 5.3y - 3z = 18\n2x + 3y - 2z = 8\n3x + 5y - 3z = 0\n'