In [2]:
import numpy as np

In [5]:
a = np.zeros(5)

In [6]:
a.ndim

1

In [7]:
a

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
b = np.zeros((3,4))

In [11]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
b.ndim

2

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [19]:
arr = np.zeros((3,4))

In [20]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
arr.ndim

2

In [22]:
#3d array


In [23]:
np.zeros(4)

array([0., 0., 0., 0.])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
arr3 = np.zeros((1,3,4))

In [55]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [56]:
arr3.ndim

3

In [57]:
d = np.zeros((1,2,2,3))

In [58]:
d.ndim

4

In [59]:
d

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [60]:
c = np.zeros((1,1,1,3,3))

In [61]:
c 

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [62]:
c.ndim

5

In [63]:
arr = np.zeros((3,5))

In [64]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
arr+5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [66]:
a = arr+5

In [67]:
a * 2

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [68]:
a - 1

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [ ]:
np.eye(3) #return a 2-d array with onces on the diagonal and zeros elseehere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.eye(3, dtype=int) 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [72]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
np.empty((3,4)) #return a new array og given shape and type, without initiating entries. >> it menas entries in the array can be anything random values

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
#optonal >> random module
import random
random.choice((1,2,3,4,5))

5

In [78]:
random.choice('Pritam')

'r'

In [88]:
random.randrange(1,13)

2

In [90]:
random.random() #a random no grnerated between 0(include) and 1(excluded)

0.032217654382395766

In [92]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [93]:
random.shuffle(lis)

In [94]:
lis

[4, 5, 1, 2, 3]

In [95]:
random.uniform(7,14)

12.773251726414973

In [96]:
#random numbers related concept in numpy
np.array([])

array([], dtype=float64)

In [97]:
np.random.random_sample()

0.6740541674654853

In [99]:
np.random.random_sample(5,) #1D array of 5 random numders


array([0.15842924, 0.03056332, 0.57044457, 0.71288831, 0.25963628])

In [100]:
np.random.rand(1)

array([0.93736455])

In [101]:
np.random.rand(2,3)

array([[7.47928976e-05, 3.23162864e-01, 1.26998068e-01],
       [9.19323385e-01, 2.34065984e-01, 1.44525323e-01]])

In [104]:
np.random.rand(2,3) #return a sample (or sample) from the "standard" distribution

array([[0.21019602, 0.6920475 , 0.8411072 ],
       [0.86735369, 0.56641711, 0.84751371]])

In [105]:
np.random.randint(1,5)

1

In [107]:
arr = np.random.randint(1,5, size = (3,5)) #start from 1 and end at 5-1 and give array of shape 3,4

In [108]:
arr.ndim

2

In [109]:
arr.shape

(3, 5)

In [110]:
arr.size

15

In [111]:
arr

array([[1, 2, 1, 1, 2],
       [1, 2, 2, 4, 4],
       [2, 3, 4, 3, 4]], dtype=int32)

In [117]:
#reshaping of array
arr1 = arr.reshape(5, 3) #returns an array containing the same data with a new shape.

In [118]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [2, 2, 4],
       [4, 2, 3],
       [4, 3, 4]], dtype=int32)

In [119]:
arr1.size

15

In [120]:
arr1.shape

(5, 3)

In [121]:
arr1.ndim

2

In [122]:
#array size will never change, always reshape parameter should be multiplication of original array size

In [123]:
arr

array([[1, 2, 1, 1, 2],
       [1, 2, 2, 4, 4],
       [2, 3, 4, 3, 4]], dtype=int32)

In [137]:
#case when we dont know in replace what should be the row or column count
#use any negative values for rows or columns
arr.reshape(3,-1)

array([[1, 2, 1, 1, 2],
       [1, 2, 2, 4, 4],
       [2, 3, 4, 3, 4]], dtype=int32)

In [138]:
arr.reshape(3,-100)

array([[1, 2, 1, 1, 2],
       [1, 2, 2, 4, 4],
       [2, 3, 4, 3, 4]], dtype=int32)

In [139]:
arr.reshape(-1,5)

array([[1, 2, 1, 1, 2],
       [1, 2, 2, 4, 4],
       [2, 3, 4, 3, 4]], dtype=int32)

In [140]:
arr.reshape(3,-1).base #to see the original array

array([[1, 2, 1, 1, 2],
       [1, 2, 2, 4, 4],
       [2, 3, 4, 3, 4]], dtype=int32)

In [124]:
arr.reshape(1,5,3)

array([[[1, 2, 1],
        [1, 2, 1],
        [2, 2, 4],
        [4, 2, 3],
        [4, 3, 4]]], dtype=int32)

In [125]:
arr_n = np.random.randint(1,5, size = (4,4))

In [126]:
arr_n

array([[2, 2, 3, 3],
       [2, 4, 1, 2],
       [3, 1, 4, 4],
       [2, 3, 1, 4]], dtype=int32)

In [128]:
arr_n.size

16

In [141]:
arr_n.reshape(2,2,4) #multiplication should be equal to arr_n size

array([[[2, 2, 3, 3],
        [2, 4, 1, 2]],

       [[3, 1, 4, 4],
        [2, 3, 1, 4]]], dtype=int32)

In [143]:
arr_n.reshape(1,2,2,4)

array([[[[2, 2, 3, 3],
         [2, 4, 1, 2]],

        [[3, 1, 4, 4],
         [2, 3, 1, 4]]]], dtype=int32)

In [148]:
d4 = arr_n.reshape(2,2,2,2)
d4


array([[[[2, 2],
         [3, 3]],

        [[2, 4],
         [1, 2]]],


       [[[3, 1],
         [4, 4]],

        [[2, 3],
         [1, 4]]]], dtype=int32)

In [149]:
d4.ndim

4

In [152]:
#condition on array
arr_1 = np.random.randint(1,10, (5,6))

In [153]:
arr_1

array([[5, 1, 8, 1, 5, 5],
       [6, 4, 1, 3, 5, 3],
       [2, 1, 3, 4, 3, 1],
       [9, 2, 7, 2, 2, 5],
       [2, 4, 6, 7, 9, 1]], dtype=int32)

In [154]:
arr_1.shape

(5, 6)

In [155]:
arr_1.size

30

In [156]:
arr_1.ndim

2

In [157]:
arr_1

array([[5, 1, 8, 1, 5, 5],
       [6, 4, 1, 3, 5, 3],
       [2, 1, 3, 4, 3, 1],
       [9, 2, 7, 2, 2, 5],
       [2, 4, 6, 7, 9, 1]], dtype=int32)

In [159]:
arr_1 > 3

array([[ True, False,  True, False,  True,  True],
       [ True,  True, False, False,  True, False],
       [False, False, False,  True, False, False],
       [ True, False,  True, False, False,  True],
       [False,  True,  True,  True,  True, False]])

In [163]:
arr_1[arr_1 > 3] #select all the element of arr1 where the condition is true

array([5, 8, 5, 5, 6, 4, 5, 4, 9, 7, 5, 4, 6, 7, 9], dtype=int32)

In [164]:
arr_1[arr_1 < 3]

array([1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1], dtype=int32)

In [165]:
arr_1

array([[5, 1, 8, 1, 5, 5],
       [6, 4, 1, 3, 5, 3],
       [2, 1, 3, 4, 3, 1],
       [9, 2, 7, 2, 2, 5],
       [2, 4, 6, 7, 9, 1]], dtype=int32)

In [166]:
#to access element in an array

In [167]:
arr_1[0]

array([5, 1, 8, 1, 5, 5], dtype=int32)

In [168]:
arr_1[1]

array([6, 4, 1, 3, 5, 3], dtype=int32)

In [170]:
arr_1[1][2]

np.int32(1)

In [172]:
arr_1

array([[5, 1, 8, 1, 5, 5],
       [6, 4, 1, 3, 5, 3],
       [2, 1, 3, 4, 3, 1],
       [9, 2, 7, 2, 2, 5],
       [2, 4, 6, 7, 9, 1]], dtype=int32)

In [173]:
arr_1[3][1]

np.int32(2)

In [174]:
arr_1

array([[5, 1, 8, 1, 5, 5],
       [6, 4, 1, 3, 5, 3],
       [2, 1, 3, 4, 3, 1],
       [9, 2, 7, 2, 2, 5],
       [2, 4, 6, 7, 9, 1]], dtype=int32)

In [175]:
#from 0th row to 2nd row
arr_1[0:3]

array([[5, 1, 8, 1, 5, 5],
       [6, 4, 1, 3, 5, 3],
       [2, 1, 3, 4, 3, 1]], dtype=int32)

In [178]:
#0 to 2nd row and 0th and 2nd column
arr_1[0:3,[0,2]]

array([[5, 8],
       [6, 1],
       [2, 3]], dtype=int32)

In [179]:
#slicing on both rows and column together
arr_1

array([[5, 1, 8, 1, 5, 5],
       [6, 4, 1, 3, 5, 3],
       [2, 1, 3, 4, 3, 1],
       [9, 2, 7, 2, 2, 5],
       [2, 4, 6, 7, 9, 1]], dtype=int32)

In [181]:
arr_1[0:3,1:4]

array([[1, 8, 1],
       [4, 1, 3],
       [1, 3, 4]], dtype=int32)

In [182]:
arr_1[0:3,[0,1]]

array([[5, 1],
       [6, 4],
       [2, 1]], dtype=int32)

In [184]:
arr_1[0,[1,3]]

array([1, 1], dtype=int32)

In [185]:
# : >> range | , perticular point

In [186]:
arr_1[2:4, [0,3]]

array([[2, 4],
       [9, 2]], dtype=int32)

In [187]:
arr_1[2:5]

array([[2, 1, 3, 4, 3, 1],
       [9, 2, 7, 2, 2, 5],
       [2, 4, 6, 7, 9, 1]], dtype=int32)

In [188]:
arr_1[2:5,0:2]

array([[2, 1],
       [9, 2],
       [2, 4]], dtype=int32)

In [ ]:
#mathametical operators on two arrays >> index wise
arr01 = np.random.randint(1,3,(3,3))
arr02 = np.random.randint(1,3,(3,3))

In [190]:
arr01

array([[1, 2, 2],
       [1, 1, 1],
       [1, 2, 2]], dtype=int32)

In [191]:
arr02

array([[2, 1, 1],
       [1, 1, 2],
       [1, 2, 1]], dtype=int32)

In [192]:
arr01 + arr02

array([[3, 3, 3],
       [2, 2, 3],
       [2, 4, 3]], dtype=int32)

In [193]:
arr01 - arr02

array([[-1,  1,  1],
       [ 0,  0, -1],
       [ 0,  0,  1]], dtype=int32)

In [194]:
arr01 * arr02

array([[2, 2, 2],
       [1, 1, 2],
       [1, 4, 2]], dtype=int32)

In [195]:
arr01, arr02

(array([[1, 2, 2],
        [1, 1, 1],
        [1, 2, 2]], dtype=int32),
 array([[2, 1, 1],
        [1, 1, 2],
        [1, 2, 1]], dtype=int32))

In [196]:
arr01/arr02

array([[0.5, 2. , 2. ],
       [1. , 1. , 0.5],
       [1. , 1. , 2. ]])

In [197]:
#matrix multiplication >> atrix is a specialised 2-d array
#matrix multiplication is different from index wise multiplication

In [198]:
arr01 @ arr02

array([[6, 7, 7],
       [4, 4, 4],
       [6, 7, 7]], dtype=int32)

In [ ]:
#another way of matrix multiplication
np.dot(arr01,arr02) 

array([[6, 7, 7],
       [4, 4, 4],
       [6, 7, 7]], dtype=int32)

In [199]:
arr01 * arr02

array([[2, 2, 2],
       [1, 1, 2],
       [1, 4, 2]], dtype=int32)

In [201]:
#broadcasting

In [207]:
arr = np.zeros((3,4),dtype=int)

In [208]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [209]:
arr+5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [210]:
arr+[1,2,3,4]

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [211]:
arr-5

array([[-5, -5, -5, -5],
       [-5, -5, -5, -5],
       [-5, -5, -5, -5]])

In [214]:
a = np.array([1,2,3,4])

In [215]:
a

array([1, 2, 3, 4])

In [216]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [217]:
arr + a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [221]:
a = np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [219]:
#transpose >> coverting rows to column and colums to rows

In [222]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [223]:
arr01

array([[1, 2, 2],
       [1, 1, 1],
       [1, 2, 2]], dtype=int32)

In [224]:
arr01.T

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 2]], dtype=int32)